### ISSUE TITLE
[Refactor] Consistent Naming

### ISSUE THREAD

**Issue by Ben-G** [plangrid/ReactiveLists#1]
This code has evolved quite a bit since the first version used in the PlanGrid app. The names of many types still refer to `Flux`, even though the library is independent of that design pattern.

Prior to the release we should rename all types to be consistent.

**Comment by anayini** [comment]
@Ben-G - I can do this really quick if we make a decision on the renaming.  Can we just drop `Flux` everywhere?

`FluxTableViewDataSource` -> `TableViewDataSource`?

**Comment by jessesquires** [comment]
👍

**Comment by anayini** [comment]
@Ben-G - Anything else required for this issue to be closed?  Is there other name refactoring you had in mind?

**Comment by Ben-G** [comment]
@anayini Potentially down the road; but we can open separate issues for that.
