### ISSUE TITLE
[Docs] write/add VISION.md

### ISSUE THREAD

**Issue by jessesquires** [plangrid/ReactiveLists#12]

**Comment by jessesquires** [comment]
@Ben-G -- also need a good "tagline" 😉

**Comment by Ben-G** [comment]
Can you give an example RE "tagline"? Do you think we need this for the VISION doc or just in general?

**Comment by jessesquires** [comment]
Ah yes, not needed for the vision doc, but for the readme and project description:

Example:

> ## IGListKit
>
> *A data-driven UICollectionView framework for building fast and flexible lists.*

![screen shot 2018-01-22 at 2 23 15 pm](https://user-images.githubusercontent.com/2301114/35247581-d2af8fda-ff7f-11e7-954d-ec3001d539be.png)

**Comment by jessesquires** [comment]
this is done. 

https://github.com/plangrid/ReactiveLists/blob/master/Guides/VISION.md
