### ISSUE TITLE
Fixes/Improvements to TableView row height

### ISSUE THREAD

**Issue by jessesquires** [plangrid/ReactiveLists#41]
Behavior here is currently confusing and the API is hard to use.

`TableViewCellViewModel` has `rowHeight` + a default protocol implementation of `44`.

`TableViewDataSource` queries this `rowHeight` per model, or returns a magic `44`:

```swift
    open func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return self._tableViewModel?[indexPath]?.rowHeight ?? 44
    }
```

It looks like this is `open` for some one-off cases in PlanGrid.

-------

### Proposed changes

- Make `TableViewCellViewModel.rowHeight` optional (this is a per-cell height)
- Add `TableViewModel.defaultRowHeight`(this is a default for *all rows* in the table)
- In `heightForRowAt indexPath:`, use cell rowHeight, otherwise use `TableViewModel.defaultRowHeight`

**Comment by jessesquires** [comment]
cc @Ben-G / @anayini

**Comment by Ben-G** [comment]
Existing is ugly and proposed changes look good! 👨‍💻

**Comment by anayini** [comment]
👍 Changes look good
