### ISSUE TITLE
[Proposal / Investigation] Switch from using Dwiftt to IGListKit/Diffing

### ISSUE THREAD

**Issue by jessesquires** [plangrid/ReactiveLists#8]

**Comment by ronaldsmartin** [comment]
Is this still necessary because #136 happened?

**Comment by jessesquires** [comment]
@ronaldsmartin good question. perhaps not, mostly because of NSObject/bridging issues.

but, let's keep this open for discussion for now

**Comment by ronaldsmartin** [comment]
Probably not going to do this since DifferenceKit is working out for us! Can reopen if we reconsider.

**Comment by jessesquires** [comment]
Also, eventually you can switch to the iOS 13 UIKit diffing

https://developer.apple.com/documentation/uikit/uitableviewdiffabledatasource

**Comment by ronaldsmartin** [comment]
Definitely! I think https://github.com/plangrid/ReactiveLists/issues/155 is more likely to come first though

**Comment by jessesquires** [comment]
I think that also requires the iOS 13 SDK actually...

(not all Swift features are available in earlier SDKs)
